package test;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test2Test {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@Before
public void setUp() {
	
	//String projectPath = System.getProperty("user.dir");
	//System.out.println("The path is: " +projectPath);
	
	//Set the location of the driver
	System.setProperty("webdriver.gecko.driver", "C:\\Users\\percy\\Desktop\\EW\\SeleniumJavaFramework\\drivers\\geckodriver\\geckodriver.exe");
	
	
 driver = new FirefoxDriver();
 js = (JavascriptExecutor) driver;
 vars = new HashMap<String, Object>();
}
@After
public void tearDown() {
 driver.quit();
}
@Test
public void test2() throws InterruptedException {
 driver.get("https://www.google.com/");
 
 driver.manage().window().setSize(new Dimension(1265, 1380));
 driver.findElement(By.name("q")).sendKeys("A B C D");
 
 driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
 Thread.sleep(3000);
 //driver.findElement(By.cssSelector(".g:nth-child(1) .LC20lb > span")).click();
 
 driver.findElement(By.cssSelector("#rso > div:nth-child(1) > div > div.r > a > h3 > span")).click();
 
 driver.findElement(By.cssSelector("#movie_player")).click();
 
 Thread.sleep(10000);
 //driver.findElement(By.cssSelector(".video-stream")).click();
 Thread.sleep(3000);
 
 driver.quit();
}
}

